apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstpod
  labels:
    app: flask
    
spec:
  template:
    metadata:
      name: firstpod
      labels:
        app: flask

    spec:
      containers:
      - name: firstpod
        image: maissa47/todo_app
  replicas: 3
  selector:
    matchLabels:
      app: flask
