apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: flask
spec:
  containers: 
    - name: firstpod
      image: maissa47/todo_app:tagVersion
      ports:
        - containerPort: 8080
