pipeline {
    agent any
   
    environment {
        registry = "maissa47/mypythonapp"
        dockerImage = ''
        registryCredential='DockerHub_ID'
    }
    stages {
        stage('checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mayssa-bm/TodoApp']]])
            }
        }
        stage('build docker image') {
            steps {
                script {
                    dockerImage = docker.build registry
                    }
            }
        }
         stage('Upload Image') {
            steps{    
                script {
                    docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                    }
                }
             }
         }
        
    }
}
