pipeline {
    agent any
    environment{
    
        DOCKER_TAG= getDockerTag()
        registry= 
        registryCredentials= "nexus"
    }
    stages {
        stage('checkout') {
            steps {
               // checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mayssa-bm/TodoApp']]])
            }
        }
       
        stage('Build Docker image'){
            steps{
                sh "docker build . -t maissa47/todo-app:${DOCKER_TAG}"
            }
        }
       
         // Uploading Docker images into Nexus Registry
        stage('Uploading to Nexus') {
            steps{  
                script {
                    docker.withRegistry( 'http://'+registry, registryCredentials ) {
                    dockerImage.push('latest')
                    }
                }
            }     
        }

        //stage('Deploy to k8s') {
          //  steps{
            //    sh "chmod +x changeTag.sh"
             //   sh "./changeTag.sh ${DOCKER_TAG}"
            //}
            //}

    }
}

def getDockerTag(){
    def tag = sh script: 'git rev-parse HEAD', returnStdout: true
    return tag
}