pipeline {
    agent any
   
    environment{
    
        DOCKER_TAG= getDockerTag()
        registryCredential='DockerHub_ID'

    }
   
    stages {
        stage('checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mayssa-bm/k8s-CICD']]])
            }
        }
       stage('Build Docker image'){
            steps{
                script{
                    sh "docker build . -t maissa47/todo-app:${DOCKER_TAG}"
                }
             
                
            }
        }
        stage('Push Image') {
            steps{    
                script{
                    docker.withRegistry( '', registryCredential ) {
                    sh "docker push maissa47/todo-app:${DOCKER_TAG}"
                    } 
                }
                 
            }
        }
    }
}

def getDockerTag(){
    def tag = sh script: 'git rev-parse HEAD', returnStdout: true
    return tag
}

