# Setting host
- hosts: localhost
  gather_facts: false
#Variables
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: firstpod
    image_tag: latest
    replicas: 1
# Pre-Tasks to validate if Minikube is running
  pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    # Otherwise will start minikube
    - name: Start Minikube if it's not running.
      command: minikube start
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

  tasks:
  #create jenkins and devops-tools
    - name: Create jenkins namespace
      community.kubernetes.k8s:
        name: jenkins
        api_version: v1
        kind: Namespace
        state: present
     - name: Create devops-tools namespace
      community.kubernetes.k8s:
        name: devops-tools
        api_version: v1
        kind: Namespace
        state: present
  #setup deployment
  - name: Create a jenkins Deployment 
    community.kubernetes.k8s:
      state: present
      src: /jenkins/jenkins.deployment.yaml 
  - name: Create a nexus Deployment 
    community.kubernetes.k8s:
      state: present
      src: /nexus/nexus.deployment.yaml 
  #setup services
  - name: Create a Jenkins Service 
    community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: jenkins
          spec:
            type: NodePort
            ports:
             - port: 8080
               targetPort: 8080
            selector:
               app: jenkins
  - name: Create a nexus Service 
    community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nexus-service
            namespace: devops-tools
            annotations:
              prometheus.io/scrape: 'true'
              prometheus.io/path:   /
              prometheus.io/port:   '8081'
          spec:
            selector: 
              app: nexus-server
            type: NodePort  
            ports:
            - port: 8081
              targetPort: 8081
              nodePort: 32000
      