pipeline {
    agent any
    environment{
    
        DOCKER_TAG= getDockerTag()
        //registry='ip address'
        registryCredentials ='nexus-id'
    }
    stages {
        stage('checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mayssa-bm/TodoApp']]])
            }
        }
       
        stage('Build Docker image'){
            steps{
                sh "docker build . -t maissa47/todo-app:${DOCKER_TAG}"
                
            }
        }

         stage('Uploading to Nexus') {
            steps{  
                script {
                    docker.withRegistry( 'http://'+registry, registryCredentials ) {
                    sh "docker push maissa47/todo-app:${DOCKER_TAG}"
                     }
                }
            }
         }
    }
}

def getDockerTag(){
    def tag = sh script: 'git rev-parse HEAD', returnStdout: true
    return tag
}